services:
  - type: static
    name: infistel-atencion-cliente
    repo: https://github.com/infistelsac/atencioncliente # Render will use the connected repo
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: VITE_FIREBASE_CONFIG
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
